### ISSUE TITLE
Need Flyers

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#2]
We need flyers for the event. I have emailed the previous years flyers in case Lily doesn't have time.

**Comment by robfitzgerald** [comment]
Great. I'm on it. I like this format already. :+1:

**Comment by robfitzgerald** [comment]
@Wmaxlees what exact date time did we settle on?  august 25th at [time] o'clock?

**Comment by Wmaxlees** [comment]
Did we say 5:30? I didn't write it down

**Comment by minor-jason** [comment]
I wrote down 5:30

**Comment by robfitzgerald** [comment]
emailed lily about the flier

**Comment by robfitzgerald** [comment]
lily's gonna do the flyer.

**Comment by robfitzgerald** [comment]
flyers from lily:  https://drive.google.com/folderview?id=0BxY5K8uxLychfkZrQUVzRFNadDhVRkduUUVLMEdNUlY4V1F2cDd4cTV5eWRkOXU4d0NFeGM&usp=sharing

**Comment by robfitzgerald** [comment]
hey guys, do we want to do the raffle like last semester?
... did we do the raffle last semester?
it's still listed on this flyer.

**Comment by Wmaxlees** [comment]
We ended up giving people gift cards to iPie. Also, it still says contact Nathan.

**Comment by robfitzgerald** [comment]
oh good call there

**Comment by robfitzgerald** [comment]
sent iPie update to lily

**Comment by robfitzgerald** [comment]
reminder email sent to lily (cuz we're 8 days out)

**Comment by robfitzgerald** [comment]
we don't have an issue for "send out orgsync email for trivia night" so i'll put this here.  when we do put that out, let's also mention that we are nominating Lily Dam for our treasurer position, and will accept additional nominations and hold a vote at the upcoming Trivia Night.

do you guys approve of that idea?

**Comment by Wmaxlees** [comment]
Did Lily say she's interested? If she is, I think the idea is good.

**Comment by robfitzgerald** [comment]
oh yes, sorry if i didn't add that detail.  she is interested, wants to know more, asked me if we could talk maybe at the next event.  i sent her an email with the job description from the bylaws doc, plus a description of our collaborative process, hoping she would have a clear picture of it in time for that meeting.

found this in the bylaws as well:
1.  Vacancies in any office other than the Chair caused by resignation, removal or disability shall be filled by an election that will take place at the next possible chapter-wide meeting. If the office of Chair is so vacated, the Vice Chair shall immediately assume that office, and the chapter shall elect a new Vice Chair

so we could skip the nomination process really, i just figure, we probably want to give some kind of heads up about the election in whatever next communication we make to members.

**Comment by Wmaxlees** [comment]
Sounds good to me. So the position of Chair just needs to be 'vacated' and I'll get the position? I'm going to bring you a definitely-not-poisoned brownie on Wednesday.

**Comment by robfitzgerald** [comment]
ya, all this time (as in, for, like the last few months), you've had a countably infinite number of opportunities.

**Comment by robfitzgerald** [comment]
but, the cardinality of the power set of those possibilities is not countably infinite.

**Comment by robfitzgerald** [comment]
(DROPS MIC)

**Comment by Wmaxlees** [comment]
(slow clap)

**Comment by robfitzgerald** [comment]
thank you, thank you.

**Comment by robfitzgerald** [comment]
Printed and a few posted
