### ISSUE TITLE
Find New Officer

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#4]
Find a new officer to receive national recognition from ACM

**Comment by robfitzgerald** [comment]
@Wmaxlees @minor-jason, when we find a treasurer, do we want to include them in our core team work?

**Comment by Wmaxlees** [comment]
If they would like to be involved, I think that's fine. I'm not sure we'll find someone if that's a requirement, though.

**Comment by Wmaxlees** [comment]
Now that I think about it, though. The treasurer should at least keep a running excel spreadsheet (or whatever the google doc version of that is) in our ucd.acm drive of the current chapter funds. I think that would be an appropriate amount of work for a treasurer, right?

**Comment by robfitzgerald** [comment]
i agree w/ treasurer doing treasurer job at minimum.
should we ask lily?  again, she's supposed to have been an officer since april.  i think we can register that role retroactively at the ACM site.  if she's into just keeping that updated, and she still wants to do graphic design, that sounds like enough to be given an officer role.

**Comment by Wmaxlees** [comment]
I think Lily is a good choice

**Comment by minor-jason** [comment]
She has certainly done enough to deserve it.

**Comment by robfitzgerald** [comment]
my only trailing thought about appointing lily to treasurer is that there is also a formalized ACM officer role for webmaster.  if we get the site running and need a webmaster, maybe we could offer the role to her first, because she might appeal to it.

but, that said, if you two aren't against it, i'll ask lily if she would accept the nomination.  and, then ~~we~~ i could put out a call for treasurer nominations and list her as the ACM officer nomination.

**Comment by robfitzgerald** [comment]
just because i was thinking of it i made a treasury doc.  shared to jason max and ucd.acm accounts

**Comment by Wmaxlees** [comment]
I'm fine with her doing which ever one she prefers. We can probably find someone else to fill the other position

**Comment by robfitzgerald** [comment]
k i'll put it all out on the table then.

**Comment by robfitzgerald** [comment]
all work beyond this falls under "contact lily"
