### ISSUE TITLE
Compile panel event participant list and schedule participants

### ISSUE THREAD

**Issue by minor-jason** [acm-ucdenver/events#51]

**Comment by robfitzgerald** [comment]
Shawn McCarthy, James Jamison, Doug Williams all in so far

**Comment by robfitzgerald** [comment]
emailed Shawn, James, and Doug with dates.

**Comment by robfitzgerald** [comment]
shawn says: "Preference order: Nov 3rd, October 30th, Nov 5th"
james's assistant says: "both of the November dates will work.  Neither of the Oct dates will work, unfortunately."

november 3rd is winning so far.

**Comment by robfitzgerald** [comment]
eric is suggesting thursday or friday.

from those 3, we could say nov 3 and get shawn/james; we could say oct 30 and get eric/shawn; we could ask eric if he can do tues nov 3 because we are running into conflicts.  i would prioritize james, shawn: james' event idea, and shawn is bringing food.

no word yet from doug.

let's think on it a night!

**Comment by robfitzgerald** [comment]
core 3 panelists confirmed.  sending out confirmation emails to them.
