### ISSUE TITLE
Respond to Amir from Google

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#52]
Amir is asking for a list of people we think they should get in touch with re: 2016 positions @ Googs.

Let's come up with a list this week.

**Comment by robfitzgerald** [comment]
any recommendations?

Here's mine: Jason Minor

**Comment by robfitzgerald** [comment]
how about
Nicole C
Sean K
Michael H
Joey V

**Comment by minor-jason** [comment]
Joe Z
Paul R
Matt L
Eric N

Jason M

**Comment by minor-jason** [comment]
Corey C
Raph O

**Comment by robfitzgerald** [comment]
:+1:

**Comment by robfitzgerald** [comment]
should max or i reply with the list so we can rep you, jason (versus reppin yourself)?

**Comment by minor-jason** [comment]
That's probably not a bad idea.

**Comment by robfitzgerald** [comment]
i'll take a stab at an email and share it here

**Comment by Wmaxlees** [comment]
:+1: I'll take a look at the email when you post it.

**Comment by robfitzgerald** [comment]
so far it's mostly about copying email addresses... :-P

**Comment by robfitzgerald** [comment]
paul r?

**Comment by robfitzgerald** [comment]
matt l?  i think eric's 'eric nguyen' right

**Comment by minor-jason** [comment]
Paul Rodriguez, Matt LaMont. Eric Nguyen, yes.

**Comment by minor-jason** [comment]
Who is Joey V?

**Comment by robfitzgerald** [comment]
joey is the guy who started the synaesthetics collective student group with ellen.  he's pursuing a minor in CS, currently taking boris' grad AI course with me and max.  he's also a musician.  i want to put him on this list though i've waffled about it in the last 5 - 10, because i'm wondering if i should rep someone to google who doesn't have the serious coder chops on paper.

**Comment by Wmaxlees** [comment]
I think you should add him but be honest about it. Just say he's good at theory (if you think that's the case) but that he doesn't have the coding experience you would expect from other CS students. It would be better for everyone on the list if you have listed a reason why you think they are a good pick.

**Comment by robfitzgerald** [comment]
Amir,

Hi, this is Rob Fitzgerald, Chair of the ACM of UC Denver.  Thanks again for getting in touch with us.  There has been a lot of buzz about Google's new campus in Boulder.

Here are some students we would like to recommend to you with Spring 2016 graduation dates:

nicole.cranon@ucdenver.edu
sean.khulman@ucdenver.edu
jason.minor@ucdenver.edu
michael.hunsinger@ucdenver.edu
joseph.zurawski@ucdenver.edu
paul.rodriguez@ucdenver.edu
matthew.lamont@ucdenver.edu
eric.nguyen@ucdenver.edu
joseph.verbeke@ucdenver.edu
cory.coellen@ucdenver.edu
raphael.oflynn@ucdenver.edu

In the last few years, I have been in classes with all of these students.  They are the short list of students I would cross my fingers and hope to have assigned to my group coding assignments.  All self-motivated problem solvers without complicated egos and high standings in our coursework.

Hope this list helps your selection process.  Also, if you happen to know of a community relations manager who is interested in getting in contact with us, I would greatly appreciate an introduction.

Regards,

Rob Fitzgerald
Chair, ACM of UC Denver
robert.fitzgerald@ucdenver.edu

**Comment by robfitzgerald** [comment]
um, yea, i agree. i wanted to say a little something about each one, but, i was worried about the email getting too long.  tradeoff...

**Comment by Wmaxlees** [comment]
It may be better to send 3-4 people with specific reasons why they are good rather than trying to send everyone we know

**Comment by robfitzgerald** [comment]
totally. that was my next question.  :-)

**Comment by robfitzgerald** [comment]
i would strip it down to jason and 4 others.  maybe jason you could help since you know your grade better than max and i

**Comment by Wmaxlees** [comment]
^

**Comment by Wmaxlees** [comment]
I vote Nicole as well because she goes to every event we have.

**Comment by minor-jason** [comment]
True, we probably should take "membership" into account

**Comment by robfitzgerald** [comment]
yes.  i had that thought earlier when i was thinking of adding joey, but a lot of those folks who are rock stars on the list above aren't really ACM members.  might be good to see who is on orgsync, but, when it comes to showing up: Jason. Nicole. and i most certainly can rep them, with words.  in english.

**Comment by Wmaxlees** [comment]
The only other person I know on the list is Joey V. and I don't think I've seen him at any ACM events. So I would be happy with just Jason and Nicole.

**Comment by robfitzgerald** [comment]
## take 2:

Amir,

Hi, this is Rob Fitzgerald, Chair of the ACM of UC Denver. Thanks again for getting in touch with us. There has been a lot of buzz about Google's new campus in Boulder.

Here are some student ACM members whom we would like to recommend to you, with Spring 2016 graduation dates.  They are the short list of students I would cross my fingers and hope to have assigned to my group coding assignments. All self-motivated problem solvers without complicated egos and high standings in our coursework.

Nicole Cranon - nicole.cranon@ucdenver.edu
Nicole is a very bright student, and a great team player.  She picks up new technologies quickly, isn’t overstated, and seems to have innate talent playing Soul Kalibur 4.  Nicole is currently an intern for Vantiv, a payments processor in Denver.

Jason Minor - jason.minor@ucdenver.edu
Jason is the current Secretary for our student group.  He is very articulate, friendly, but also very focused and successful student.  He will likely find himself in leadership roles wherever he ends up.  He currently has an internship with Boulder Imaging.

Greg Peters - greg.peters@ucdenver.edu
Greg is a professional ice breaker.  I am guaranteed to have a successful event when he shows up, because he knows how to get all these computer science students to start talking.  He seems to have a lot of tech projects going on, such as his home server.

Hope this list helps your selection process. Also, if you happen to know of a community relations manager who is interested in getting in contact with us, I would greatly appreciate an introduction.

Regards,

Rob Fitzgerald
Chair, ACM of UC Denver
robert.fitzgerald@ucdenver.edu

**Comment by robfitzgerald** [comment]
@Wmaxlees you said you wanted to see this draft, so, just let me know if it looks good to you.

**Comment by Wmaxlees** [comment]
When do you want to send it out. I was gonna take a look tomorrow morning if that's okay.

**Comment by robfitzgerald** [comment]
ok sure!

**Comment by Wmaxlees** [comment]
I didn't see a google doc for this so I made some edits and am just gonna repost it here: 

Amir,

Hi, this is Rob Fitzgerald, Chair of the ACM of UC Denver. Students are buzzing about Google's new campus in Boulder so we’re excited to see someone from Google reaching out to us.

Here are some ACM members whom we think would make a great addition to Google with Spring 2016 graduation dates. I would be more than happy to have any one of them on my team.

Nicole Cranon - nicole.cranon@ucdenver.edu
Nicole is a very bright student, and a great team player, and manages to pick up new technologies quickly. Her interest in CS is her biggest advantage, though. She consistently seeks out new challenges and new ways to explore the world of computers. Nicole has had CS work experience interning for Vantiv.

Jason Minor - jason.minor@ucdenver.edu
Jason is the current Secretary for our ACM Chapter. He is very articulate and friendly and on, top of that, a very focused and successful student. I believe his self-motivation and natural social skills will eventually land him in a leadership role wherever he ends up. He has had work experience interning for Boulder Imaging.

Greg Peters - greg.peters@ucdenver.edu
Greg is one of those students whom always have a lot of side projects going on, such as his home server. We think his greatest asset, however is his ability to break the ice in social situations. Our chapter events are guaranteed to be more social when he shows up because he knows how to get all these computer science students to start chatting.

Hope this list helps your selection process. Also, you mentioned a campus team that may be interested in working with us. Would you mind passing along their contact information?

Regards,
Rob Fitzgerald
Chair, ACM of UC Denver
robert.fitzgerald@ucdenver.edu
